# Generated by Django 2.2.11 on 2020-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_language',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
