# Generated by Django 2.2.11 on 2020-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
