# Generated by Django 2.2.11 on 2020-03-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_project_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
